apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-service
  labels:
    app: my-new-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-new-service
  template:
    metadata:
      labels:
        app: my-new-service
    spec:
      containers:
      - name: my-new-service
        env:
        - name: ENVIRONMENT
          value: 'prd'
        - name: BASE_URL
          value: 'https://my-site.com'
